AWSTemplateFormatVersion: 2010-09-09
Description: Compute stack for BPartners API

Parameters:
  Env:
    Type: String
  Image:
    Type: String
  ContainerName:
    Type: String
    Default: bpartners-api
  ContainerPort:
    Type: Number
    Default: 8080
  TasksDesiredCount:
    Type: Number
    Default: 1
  ListenerRuleAvailablePriority:
    Type: Number

Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Join ['', [!Ref Env, -bpartners-api]]
  LogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: "Retain"
    Properties:
      LogGroupName: !Join ['', [/ecs/, !Ref Env, -bpartners-api]]
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    DependsOn: LogGroup
    Properties:
      Family: !Join ['', [!Ref Env, -bpartners-api]]
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 256
      Memory: 0.5GB
      ExecutionRoleArn: !Ref ExecutionRole
      TaskRoleArn: !Ref TaskRole
      ContainerDefinitions:
        - Name: !Ref ContainerName
          Image: !Ref Image
          PortMappings:
            - ContainerPort: !Ref ContainerPort
          Environment:
            - Name: ENV
              Value: !Ref Env
            - Name: SENTRY_DSN
              Value: !Sub '{{resolve:ssm:/bpartners/sentry/dsn}}'
            - Name: AWS_COGNITO_USERPOOL_ID
              Value: !Sub '{{resolve:ssm:/bpartners/${Env}/cognito/userpool-id}}'
            - Name: AWS_EVENTBRIDGE_BUS
              Value: !Sub '{{resolve:ssm:/bpartners/${Env}/eventbridge/bus-name}}'
            - Name: AWS_SQS_QUEUEURL
              Value: !Sub '{{resolve:ssm:/bpartners/${Env}/sqs/api-queue-url}}'
            - Name: SPRING_DATASOURCE_URL
              Value: !Sub '{{resolve:ssm:/bpartners/${Env}/db/url}}'
            - Name: SPRING_DATASOURCE_PASSWORD
              Value: !Sub '{{resolve:ssm:/bpartners/${Env}/db/password}}'
            - Name: SWAN_CLIENT_ID
              Value: !Sub '{{resolve:ssm:/bpartners/${Env}/swan/client-id}}'
            - Name: SWAN_CLIENT_SECRET
              Value: !Sub '{{resolve:ssm:/bpartners/${Env}/swan/client-secret}}'
            - Name: AWS_SSM_SWAN_PROJECT_PARAM
              Value: !Sub '{{resolve:ssm:/bpartners/${Env}/swan/swan-project-param-name}}'
            - Name: FINTECTURE_APP_ID
              Value: !Sub '{{resolve:ssm:/bpartners/${Env}/fintecture/app-id}}'
            - Name: FINTECTURE_APP_SECRET
              Value: !Sub '{{resolve:ssm:/bpartners/${Env}/fintecture/app-secret}}'
            - Name: SENDINBLUE_API_KEY
              Value: !Sub '{{resolve:ssm:/bpartners/${Env}/sendinblue/api-key}}'
            - Name: SENDINBLUE_CONTACTLIST_ID
              Value: !Sub '{{resolve:ssm/bpartners/${Env}/sendinblue/contactlist-id}}'
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: ecs
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['', [!Ref Env, -bpartners-api, -ExecutionRole]]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['', [!Ref Env, -bpartners-api, -TaskRole]]
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
        - 'arn:aws:iam::aws:policy/AmazonSQSFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonEventBridgeFullAccess'
      Policies:
        - PolicyName: customPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - ssm:CancelCommand
                  - ssm:SendCommand
                  - ssm:ListCommands
                  - ssm:SendAutomationSignal
                  - ssm:CreateActivation
                  - ssm:ListInstanceAssociations
                  - ssm:UpdateAssociation
                  - ssm:CreateOpsItem
                  - ssm:UpdateAssociationStatus
                  - ssm:StartSession
                  - ssm:GetMaintenanceWindowTask
                  - ssm:DescribeAutomationExecutions
                  - ssm:RegisterPatchBaselineForPatchGroup
                  - ssm:DescribeMaintenanceWindowExecutionTaskInvocations
                  - ssm:DescribeAutomationStepExecutions
                  - ssm:ListResourceDataSync
                  - ssm:ListDocuments
                  - ssm:UpdateDocument
                  - ssm:DescribeMaintenanceWindowsForTarget
                  - ssm:UpdateManagedInstanceRole
                  - ssm:PutCalendar
                  - ssm:UpdatePatchBaseline
                  - ssm:ListComplianceItems
                  - ssm:GetMaintenanceWindowExecutionTask
                  - ssm:RegisterTaskWithMaintenanceWindow
                  - ssm:GetMaintenanceWindowExecution
                  - ssm:ListResourceComplianceSummaries
                  - ssm:CreateDocument
                  - ssm:DescribeOpsItems
                  - ssm:GetOpsMetadata
                  - ssm:UpdateMaintenanceWindow
                  - ssm:StartAutomationExecution
                  - ssm:DescribeMaintenanceWindows
                  - ssm:CreateAssociation
                  - ssm:CancelMaintenanceWindowExecution
                  - ssm:DescribeEffectivePatchesForPatchBaseline
                  - ssm:DescribeDocumentPermission
                  - ssm:GetAutomationExecution
                  - ssm:DescribePatchGroups
                  - ssm:GetDefaultPatchBaseline
                  - ssm:DescribeDocument
                  - ssm:ListAssociationVersions
                  - ssm:PutConfigurePackageResult
                  - ssm:DescribePatchGroupState
                  - ssm:UpdateMaintenanceWindowTask
                  - ssm:ResetServiceSetting
                  - ssm:CreatePatchBaseline
                  - ssm:DeleteInventory
                  - ssm:DescribeMaintenanceWindowExecutionTasks
                  - ssm:DescribeInstancePatchStatesForPatchGroup
                  - ssm:GetDocument
                  - ssm:CreateResourceDataSync
                  - ssm:GetInventorySchema
                  - ssm:CreateMaintenanceWindow
                  - ssm:GetMaintenanceWindow
                  - ssm:GetParametersByPath
                  - ssm:DescribeAssociationExecutionTargets
                  - ssm:GetPatchBaseline
                  - ssm:ListInventoryEntries
                  - ssm:DescribeAssociation
                  - ssm:ListOpsItemEvents
                  - ssm:DescribeSessions
                  - ssm:DisassociateOpsItemRelatedItem
                  - ssm:DescribePatchBaselines
                  - ssm:DeregisterPatchBaselineForPatchGroup
                  - ssm:GetOpsSummary
                  - ssm:DescribePatchProperties
                  - ssm:StopAutomationExecution
                  - ssm:UpdateOpsItem
                  - ssm:UpdateServiceSetting
                  - ssm:DescribeInstanceInformation
                  - ssm:ListTagsForResource
                  - ssm:CreateAssociationBatch
                  - ssm:DescribeDocumentParameters
                  - ssm:GetCalendar
                  - ssm:RegisterDefaultPatchBaseline
                  - ssm:GetCalendarState
                  - ssm:UpdateInstanceAssociationStatus
                  - ssm:LabelParameterVersion
                  - ssm:ResumeSession
                  - ssm:ListDocumentVersions
                  - ssm:DeregisterTargetFromMaintenanceWindow
                  - ssm:UpdateDocumentDefaultVersion
                  - ssm:ListDocumentMetadataHistory
                  - ssm:DescribeMaintenanceWindowSchedule
                  - ssm:DescribeInstancePatches
                  - ssm:UpdateMaintenanceWindowTarget
                  - ssm:GetParameter
                  - ssm:GetMaintenanceWindowExecutionTaskInvocation
                  - ssm:DeleteActivation
                  - ssm:DeleteParameter
                  - ssm:StartAssociationsOnce
                  - ssm:UnlabelParameterVersion
                  - ssm:UpdateInstanceInformation
                  - ssm:ListOpsMetadata
                  - ssm:DescribeParameters
                  - ssm:PutComplianceItems
                  - ssm:GetConnectionStatus
                  - ssm:GetOpsItem
                  - ssm:DeleteOpsMetadata
                  - ssm:RegisterTargetWithMaintenanceWindow
                  - ssm:GetParameters
                  - ssm:ListOpsItemRelatedItems
                  - ssm:DeleteParameters
                  - ssm:PutParameter
                  - ssm:UpdateResourceDataSync
                  - ssm:GetServiceSetting
                  - ssm:StartChangeRequestExecution
                  - ssm:DescribeAssociationExecutions
                  - ssm:ListCommandInvocations
                  - ssm:UpdateOpsMetadata
                  - ssm:DescribeMaintenanceWindowTasks
                  - ssm:GetPatchBaselineForPatchGroup
                  - ssm:TerminateSession
                  - ssm:AssociateOpsItemRelatedItem
                  - ssm:DeletePatchBaseline
                  - ssm:DescribeMaintenanceWindowExecutions
                  - ssm:GetManifest
                  - ssm:DescribeInstancePatchStates
                  - ssm:DeleteResourceDataSync
                  - ssm:RegisterManagedInstance
                  - ssm:DeregisterTaskFromMaintenanceWindow
                  - ssm:DescribeInstanceAssociationsStatus
                  - ssm:DescribeInstanceProperties
                  - ssm:GetDeployablePatchSnapshotForInstance
                  - ssm:GetParameterHistory
                  - ssm:DescribeMaintenanceWindowTargets
                  - ssm:DeleteMaintenanceWindow
                  - ssm:DescribeInventoryDeletions
                  - ssm:DescribeEffectiveInstanceAssociations
                  - ssm:GetInventory
                  - ssm:DescribeActivations
                  - ssm:GetCommandInvocation
                  - ssm:DeregisterManagedInstance
                  - ssm:CreateOpsMetadata
                  - ssm:DeleteAssociation
                  - ssm:UpdateDocumentMetadata
                  - ssm:ListComplianceSummaries
                  - ssm:PutInventory
                  - ssm:ListAssociations
                  - ssm:DeleteDocument
                  - ssm:DescribeAvailablePatches
                Resource: arn:aws:ssm:*:*:*
                Effect: Allow
  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      ServiceName: bpartners-api
      DesiredCount: !Ref TasksDesiredCount
      TaskDefinition: !Ref TaskDefinition
      LaunchType: 'FARGATE'
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: 'ENABLED'
          SecurityGroups:
            - !Sub '{{resolve:ssm:/bpartners/${Env}/sg-id}}'
          Subnets:
            - !Sub '{{resolve:ssm:/bpartners/${Env}/subnet-id}}'
      LoadBalancers:
        - ContainerName: !Ref ContainerName
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref TargetGroup
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      Name: !Join ['', [!Ref Env, -bpartners-api, -tg]]
      Protocol: HTTP
      Port: !Ref ContainerPort
      # TargetType must be ip with Fargate: targets are (de-)registered on container creation/destruction
      TargetType: ip
      #Targets: 
      #  - AvailabilityZone: all
      #    Id: 
      #    Port: ! Ref ContainerPort
      VpcId: !Sub '{{resolve:ssm:/bpartners/${Env}/vpc-id}}'
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /ping
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 15
      HealthyThresholdCount: 2
      # Spring boot takes up to 70 seconds to start: define UnhealthyThresholdCount*HealthCheckIntervalSecond accordingly
      UnhealthyThresholdCount: 4
  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Sub '{{resolve:ssm:/bpartners/${Env}/alb-https-listener-arn}}'
      Priority: !Ref ListenerRuleAvailablePriority
      Conditions:
        - Field: host-header
          HostHeaderConfig:
            Values:
              - !Join ['', [api-, !Ref Env, .bpartners.app]]
      Actions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
