AWSTemplateFormatVersion: 2010-09-09
Description: Stack for BPartners API

Parameters:
  Env:
    Type: String

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['', [ !Ref Env, -bpartners]]
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: !Join [ '', [ !Ref Env, -bpartners-api ] ]