openapi: 3.0.3
info:
  version: '1.0'
  title: BPartners API
servers:
  - url: 'https://api-dev.bpartners.app'
security:
  - BearerAuth: [ ]
paths:
  /ping:
    get:
      tags:
        - Security
      summary: pong
      operationId: ping
      security: [ ] # No security
      description: Check the server health
      responses:
        '200':
          description: pong
          content:
            text/plain:
              schema:
                type: string
                example: pong
        '500':
          $ref: '#/components/responses/500'
  /auth:
    post:
      tags:
        - Security
      summary: Identify a registered user
      operationId: authentication
      security: [ ] #No security
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthParams'
        required: true
      responses:
        '200':
          description: Informations about auth link
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RedirectionComponent'
        '400':
          $ref: '#/components/schemas/BadRequestException'
        500:
          $ref: '#/components/schemas/InternalServerException'
  /token:
    post:
      tags:
        - Security
      summary: Generate a new token
      operationId: generateToken
      security: [ ] #No security
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenParams'
        required: true
      responses:
        '200':
          description: The generated token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '400':
          $ref: '#/components/schemas/BadRequestException'
        500:
          $ref: '#/components/schemas/InternalServerException'
  /onboarding:
    post:
      tags:
        - Users
      summary: Onboard new users
      operationId: onboardUsers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OnboardingParams'
        required: true
      responses:
        '200':
          description: Informations about onboarding link
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RedirectionComponent'
        '500':
          $ref: '#/components/responses/500'
  /whoami:
    get:
      tags:
        - Security
      summary: Who Am I ? Tells you who you are
      operationId: whoami
      responses:
        '200':
          description: Who you are.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Whoami'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
  /preUsers:
    get:
      tags:
        - PreUsers
      summary: Get all pre-registered users.
      operationId: getPreUsers
      parameters:
        - name: page
          in: query
          schema:
            $ref: '#/components/schemas/Page'
          required: true
        - name: page_size
          in: query
          schema:
            $ref: '#/components/schemas/PageSize'
          required: true
        - name: firstName
          in: query
          schema:
            type: string
          required: false
        - name: lastName
          in: query
          schema:
            type: string
          required: false
        - name: email
          in: query
          schema:
            type: string
          required: false
        - name: society
          in: query
          schema:
            type: string
          required: false
        - name: phoneNumber
          in: query
          schema:
            type: string
          required: false
      responses:
        '200':
          description: List of pre-registered users.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PreUser'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
    post:
      tags:
        - PreUsers
      security: [ ] #no security
      summary: Pre-register a user.
      operationId: createPreUsers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CreatePreUser'
      responses:
        200:
          description: Pre-registered user created!
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PreUser'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
  /accounts:
    get:
      tags:
        - Accounts
      summary: Get authenticated user's accounts.
      operationId: getAccounts
      responses:
        '200':
          description: List of authenticated user' s accounts.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
  /transactions:
    get:
      tags:
        - Payments
      summary: Get authenticated user' s transactions.
      operationId: getTransactions
      responses:
        '200':
          description: List of authenticated user' s transactions.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  responses:
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadRequestException'
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NotAuthorizedException'
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResourceNotFoundException'
    '429':
      description: Too many requests to the API
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TooManyRequestsException'
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InternalServerException'
  schemas:
    SwanTransaction:
      type: object
      properties:
        swanTransactionId:
          type: string
          example: 'uuid'
        amount:
          type: number
        currency:
          type: string
          example: 'EUR'
        label:
          type: string
        reference:
          type: string
        paymentDatetime:
          type: string
          format: date-time
    Transaction:
      allOf:
        - $ref: '#/components/schemas/SwanTransaction'
      type: object
      properties:
        category:
          $ref: '#/components/schemas/TransactionCategory'
    TransactionCategory:
      type: object
      properties:
        id:
          type: string
        label:
          type: string
    User:
      allOf:
        - $ref: '#/components/schemas/SwanUser'
      properties:
        id:
          type: string
          example: 'uuid'
        monthlySubscription:
          type: integer
          default: 5
        status:
          $ref: '#/components/schemas/EnableStatus'
    Account:
      allOf:
        - $ref: '#/components/schemas/SwanAccount'
    SwanAccountHolder:
      type: object
      properties:
        accountHolderName:
          type: string
        address:
          type: string
        city:
          type: string
        postalCode:
          type: string
    SwanUser:
      type: object
      properties:
        swan_id:
          type: string
          example: 'uuid'
        firstName:
          type: string
          example: 'John'
        lastName:
          type: string
          example: 'Doe'
        birthDate:
          type: string
          format: date
        idVerified:
          type: boolean
        identificationStatus:
          type: string
          example: 'ValidIdentity'
        nationalityCCA3:
          type: string
          example: 'FRA'
        mobilePhoneNumber:
          type: string
          example: "+33 1 23 45 67 89"
    SwanAccount:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        IBAN:
          type: string
        BIC:
          type: string
    EnableStatus:
      type: string
      enum:
        - ENABLED
        - DISABLED
    Whoami:
      properties:
        bearerToken:
          type: string
        user:
          $ref: '#/components/schemas/User'
    CreatePreUser:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        society:
          type: string
        email:
          type: string
          example: username@domain.com
        phoneNumber:
          type: string
    PreUser:
      allOf:
        - $ref: '#/components/schemas/CreatePreUser'
      type: object
      properties:
        id:
          type: string
        entranceDatetime:
          type: string
          format: date-time
    AuthParams:
      type: object
      properties:
        phoneNumber:
          type: string
        successUrl:
          type: string
        failureUrl:
          type: string
    OnboardingParams:
      type: object
      properties:
        successUrl:
          type: string
        failureUrl:
          type: string
    TokenParams:
      type: object
      properties:
        code:
          type: string
        successUrl:
          type: string
        failureUrl:
          type: string
    RedirectionComponent:
      type: object
      properties:
        redirectionUrl:
          type: string
        successUrl:
          type: string
        failureUrl:
          type: string
    Token:
      type: object
      properties:
        idToken:
          type: string
        accessToken:
          type: string
        refreshToken:
          type: string
        expiresIn:
          type: string
        scope:
          type: string
        tokenType:
          type: string
    Page:
      type: integer
      description: Start at `1`
    PageSize:
      type: integer
      description: Cannot exceed `500`
    Exception:
      type: object
      properties:
        type:
          type: string
        message:
          type: string
    BadRequestException:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        type: BadRequestException
        message: Bad request
    NotAuthorizedException:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        type: NotAuthorizedException
        message: Not authorized
    ResourceNotFoundException:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        type: ResourceNotFoundException
        message: Resource of type <T> identified by <I> not found
    TooManyRequestsException:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        type: TooManyRequestsException
        message: Too many requests
    InternalServerException:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        type: InternalServerException
        message: Unexpected error