openapi: 3.0.3
info:
  version: 'latest'
  title: BPartners API
servers:
  - url: https://api-dev.bpartners.app
security:
  - BearerAuth: [ ]

paths:
  #############################################
  ############### Security API ################
  #############################################
  /ping:
    $ref: './security-api.yml#/operations/ping'
  /authInitiation:
    $ref: './security-api.yml#/operations/initiateAuth'
  /token:
    $ref: './security-api.yml#/operations/createToken'
  /whoami:
    $ref: './security-api.yml#/operations/whoami'

  #############################################
  ############## Onboarding API ###############
  #############################################
  /onboardingInitiation:
    $ref: './onboarding-api.yml#/operations/initiateOnboarding'
  /preUsers:
    $ref: './onboarding-api.yml#/operations/createPreUsers'

  #############################################
  ############ User Accounts API ##############
  #############################################
  /users/{id}:
    $ref: './userAccounts-api.yml#/operations/getUserById'
  /users/{id}/accounts:
    $ref: './userAccounts-api.yml#/operations/getAccountsByUserId'
  /users/{userId}/accounts/{accountId}/accountHolders:
    $ref: './userAccounts-api.yml#/operations/getAccountHolders'
  /users/{userId}/accounts/{accountId}/accountHolders/{ahId}/companyInfo:
    $ref: './userAccounts-api.yml#/operations/updateCompanyInfo'
  /users/{userId}/accounts/{accountId}/accountHolders/{ahId}/revenueTargets:
    $ref: './userAccounts-api.yml#/operations/updateRevenueTargets'
  /businessActivities:
    $ref: './userAccounts-api.yml#/operations/getBusinessActivities'
  /users/{userId}/accounts/{accountId}/accountHolders/{ahId}/businessActivities:
    $ref: './userAccounts-api.yml#/operations/updateBusinessActivities'
  /users/{id}/legalFiles:
    $ref: './userAccounts-api.yml#/operations/getLegalFiles'
  /users/{uId}/legalFiles/{lId}:
    $ref: './userAccounts-api.yml#/operations/approveLegalFile'


  #############################################
  ################ Paying API #################
  #############################################
  /accounts/{id}/transactions:
    $ref: './paying-api.yml#/operations/getTransactions'
  /accounts/{aId}/transactions/{tId}/invoices/{iId}:
    $ref: './paying-api.yml#/operations/justifyTransaction'
  /accounts/{aId}/transactionsSummary:
    $ref: './paying-api.yml#/operations/getTransactionsSummary'
  /accounts/{aId}/invoiceRelaunchConf:
    $ref: './paying-api.yml#/operations/accountRelaunchOperations'
  /accounts/{aId}/transactionCategories:
    $ref: './paying-api.yml#/operations/getTransactionCategories'
  /accounts/{aId}/transactions/{tId}/transactionCategories:
    $ref: './paying-api.yml#/operations/createTransactionCategories'
  /accounts/{id}/products:
    $ref: './paying-api.yml#/operations/productOperations'
  /accounts/{aId}/invoices:
    $ref: './paying-api.yml#/operations/getInvoices'
  /accounts/{aId}/invoices/{iId}:
    $ref: './paying-api.yml#/operations/invoiceOperations'
  /accounts/{aId}/invoices/{iId}/relaunchConf:
    $ref: './paying-api.yml#/operations/invoiceRelaunchConfOperations'
  /accounts/{aId}/invoices/{iId}/relaunches:
    $ref: './paying-api.yml#/operations/getRelaunches'
  /accounts/{aId}/invoices/{iId}/relaunch:
    $ref: './paying-api.yml#/operations/relaunchInvoice'
  /accounts/{id}/paymentInitiations:
    $ref: './paying-api.yml#/operations/paymentInitiationsOperations'

  #############################################
  ################# Files API #################
  #############################################
  /accounts/{aId}/files/{id}:
    $ref: './files-api.yml#/operations/getFileById'
  /accounts/{aId}/files/{id}/raw:
    $ref: './files-api.yml#/operations/downloadOrUploadFile'

  #############################################
  ############## Customers API ################
  #############################################
  /accounts/{id}/customers:
    $ref: './customers-api.yml#/operations/getOrCreateCustomers'

  #############################################
  ############# Prospecting API ###############
  #############################################
  /accounts/{id}/marketplaces:
    $ref: './prospecting-api.yml#/operations/getMarketplaces'
  /accountHolders/{ahId}/prospects:
    $ref: './prospecting-api.yml#/operations/prospectOperations'
  /accountHolders/{ahId}/prospects/{id}/prospectConversion:
    $ref: './prospecting-api.yml#/operations/convertProspect'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  responses:
    400:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadRequestException'
    403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NotAuthorizedException'
    404:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResourceNotFoundException'
    429:
      description: Too many requests to the API
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TooManyRequestsException'
    500:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InternalServerException'
  schemas:
    RedirectionStatusUrls:
      type: object
      properties:
        successUrl:
          type: string
        failureUrl:
          type: string
    Redirection:
      type: object
      properties:
        redirectionUrl:
          type: string
        redirectionStatusUrls:
          $ref: '#/components/schemas/RedirectionStatusUrls'
    Page:
      type: integer
      description: Start at `1`
    PageSize:
      type: integer
      description: Cannot exceed `500`
    Exception:
      type: object
      properties:
        type:
          type: string
        message:
          type: string
    BadRequestException:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        type: BadRequestException
        message: Bad request
    NotAuthorizedException:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        type: NotAuthorizedException
        message: Not authorized
    ResourceNotFoundException:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        type: ResourceNotFoundException
        message: Resource of type <T> identified by <I> not found
    TooManyRequestsException:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        type: TooManyRequestsException
        message: Too many requests
    InternalServerException:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        type: InternalServerException
        message: Unexpected error
