package app.bpartners.api.model;

public enum WhiteListScope {
  SUBSCRIPTION_VALIDATION_NOT_REQUIRED,
  CREDIT_ANALYSIS_NOT_REQUIRED,
  PAYMENT_METHOD_NOT_REQUIRED,
  API_KEY_NOT_RESTRICTED_BY_TRIAL,
  PROSPECT_EXISTING_MAIL_CREATION_ALLOWED
}
