AWSTemplateFormatVersion: "2010-09-09"
Description: Event stack for BPartners

Parameters:
  Env:
    Type: String

Resources:
  MailboxQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join ['' , [!Ref Env , -bpartners]]
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: 5
      SqsManagedSseEnabled: false

  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName:  !Join ['' , [!Ref Env , -bpartners-dl]]
      SqsManagedSseEnabled: false

  MailboxQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref MailboxQueue
      PolicyDocument:
        Version: "2008-10-17"
        Id: "MailboxQueue_Policy"
        Statement:
          - Action:
              - "SQS:*"
            Effect: "Allow"
            Resource: !GetAtt MailboxQueue.Arn
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:root
          - Action:
              - "SQS:SendMessage"
            Effect: "Allow"
            Resource: !GetAtt MailboxQueue.Arn
            Principal:
              Service:
                - "events.amazonaws.com"
            Condition:
              ArnEquals:
                AWS:SourceArn: !GetAtt EventBridgeRule.Arn

  DeadLetterQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref DeadLetterQueue
      PolicyDocument:
        Version: "2008-10-17"
        Id: "DeadLetterQueue_Policy"
        Statement:
          - Action:
              - "SQS:*"
            Effect: "Allow"
            Resource: !GetAtt DeadLetterQueue.Arn
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:root

  MailboxQueueSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ['' , [/bpartners/ , !Ref Env , /sqs/mailbox-queue-url]]
      Type: String
      Value: !Ref MailboxQueue

  DeadLetterQueueSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ['' , [/bpartners/ , !Ref Env , /sqs/dead-letter-queue-url]]
      Type: String
      Value: !Ref DeadLetterQueue

  EventBridgeBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Join ['', [!Ref Env, -bpartners]]

  EventBridgeArchive:
    Type: AWS::Events::Archive
    Properties:
      ArchiveName: !Join ['', [!Ref Env, -bpartners, -archive]]
      SourceArn: !GetAtt EventBridgeBus.Arn

  EventBridgeRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Join ['', [!Ref Env, -bpartners, -from-api-to-api]]
      EventBusName: !GetAtt EventBridgeBus.Name
      EventPattern:
        source:
          - app.bpartners.api
      Targets:
        - Arn: !GetAtt MailboxQueue.Arn
          Id: !Join ['', [!Ref Env, -bpartners, -api-mailbox]]
      Tags:
        - Key: app
          Value: api
        - Key: env
          Value: !Ref Env

  EventBridgeBusNameSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ['',[/bpartners/ , !Ref Env , /eventbridge/bus-name]]
      Type: String
      Value: !GetAtt EventBridgeBus.Name

Outputs:
  MailboxQueueURL:
    Value: !Ref MailboxQueueSSM
  DeadLetterQueueURL:
    Value: !Ref DeadLetterQueueSSM
  EventBridgeBusName:
    Value: !Ref EventBridgeBusNameSSM
