AWSTemplateFormatVersion: 2010-09-09
Description: Bpartners - Schedulers

Parameters:
  Env:
    Type: String

Resources:
  ScheduledEventExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join [ '', [ bpartners-, !Ref Env, -ScheduledEventExecutionRole ] ]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: scheduler.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AdministratorAccess'

  RefreshInvoiceSummaryScheduler:
    Type: AWS::Scheduler::Schedule
    Properties:
      Description: Scheduler that trigger the refresh of invoices summaries
      FlexibleTimeWindow:
        Mode: "OFF"
      Name: !Join ['', [!Ref Env, -RefreshInvoiceSummary]]
      ScheduleExpression: "rate(1 hour)"
      Target:
        Arn: !Sub '{{resolve:ssm:/bpartners/${Env}/eventbridge/bus-arn}}'
        RoleArn: !GetAtt ScheduledEventExecutionRole.Arn
        DeadLetterConfig:
          Arn: !Sub '{{resolve:ssm:/bpartners/${Env}/1/sqs/dead-letter-queue-arn}}'
        EventBridgeParameters:
          DetailType: 'app.bpartners.api.endpoint.event.model.RefreshInvoiceSummaryTriggered'
          Source: 'app.bpartners.api.event1'

  RefreshTransactionSummariesScheduler:
    Type: AWS::Scheduler::Schedule
    Properties:
      Description: Scheduler that trigger the refresh of transaction summaries
      FlexibleTimeWindow:
        Mode: "OFF"
      Name: !Join [ '', [ !Ref Env, -RefreshTransactionSummaries ] ]
      ScheduleExpression: "rate(1 hour)"
      Target:
        Arn: !Sub '{{resolve:ssm:/bpartners/${Env}/eventbridge/bus-arn}}'
        RoleArn: !GetAtt ScheduledEventExecutionRole.Arn
        DeadLetterConfig:
          Arn: !Sub '{{resolve:ssm:/bpartners/${Env}/1/sqs/dead-letter-queue-arn}}'
        EventBridgeParameters:
          DetailType: 'app.bpartners.api.endpoint.event.model.RefreshTransactionsSummariesTriggered'
          Source: 'app.bpartners.api.event1'

  UpdatePaymentScheduler:
    Type: AWS::Scheduler::Schedule
    Properties:
      Description: Scheduler that trigger the update of payments
      FlexibleTimeWindow:
        Mode: "OFF"
      Name: !Join ['', [!Ref Env, -UpdatePayments]]
      ScheduleExpression: "rate(12 hours)"
      Target:
        Arn: !Sub '{{resolve:ssm:/bpartners/${Env}/eventbridge/bus-arn}}'
        RoleArn: !GetAtt ScheduledEventExecutionRole.Arn
        DeadLetterConfig:
          Arn: !Sub '{{resolve:ssm:/bpartners/${Env}/1/sqs/dead-letter-queue-arn}}'
        EventBridgeParameters:
          DetailType: 'app.bpartners.api.endpoint.event.model.UpdatePaymentTriggered'
          Source: 'app.bpartners.api.event1'

  RefreshFintectureProjectTokenScheduler:
    Type: AWS::Scheduler::Schedule
    Properties:
      Description: Scheduler that trigger the refresh of fintecture project token
      FlexibleTimeWindow:
        Mode: "OFF"
      Name: !Join ['', [!Ref Env, -RefreshFintectureToken]]
      ScheduleExpression: "rate(45 minutes)"
      Target:
        Arn: !Sub '{{resolve:ssm:/bpartners/${Env}/eventbridge/bus-arn}}'
        RoleArn: !GetAtt ScheduledEventExecutionRole.Arn
        DeadLetterConfig:
          Arn: !Sub '{{resolve:ssm:/bpartners/${Env}/1/sqs/dead-letter-queue-arn}}'
        EventBridgeParameters:
          DetailType: 'app.bpartners.api.endpoint.event.model.RefreshFintectureProjectTokenTriggered'
          Source: 'app.bpartners.api.event1'

  RelaunchProspectsScheduler:
    Type: AWS::Scheduler::Schedule
    Properties:
      Description: Scheduler that trigger the relaunch of prospects
      FlexibleTimeWindow:
        Mode: "OFF"
      Name: !Join ['', [!Ref Env, -RelaunchProspects]]
      ScheduleExpression: "cron(0 14 ? * FRI *)"
      ScheduleExpressionTimezone: "Europe/Paris"
      Target:
        Arn: !Sub '{{resolve:ssm:/bpartners/${Env}/eventbridge/bus-arn}}'
        RoleArn: !GetAtt ScheduledEventExecutionRole.Arn
        DeadLetterConfig:
          Arn: !Sub '{{resolve:ssm:/bpartners/${Env}/1/sqs/dead-letter-queue-arn}}'
        EventBridgeParameters:
          DetailType: 'app.bpartners.api.endpoint.event.model.RelaunchHoldersProspectTriggered'
          Source: 'app.bpartners.api.event1'
