AWSTemplateFormatVersion: 2010-09-09
Description: Storage stack for BPartners

Parameters:
  Env:
    Type: String
  DBName:
    Type: String
  DBClass:
    Default: db.t3.micro
    Description: Database instance class
    Type: String
    ConstraintDescription: must select a valid database instance type.
  DBSnapshot:
    Type: String

Resources:
  Database:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Retain
    Properties:
      DBName: !Ref DBName
      AllocatedStorage: '5'
      DBInstanceClass:
        Ref: DBClass
      Engine: postgres
      MasterUsername: !Sub '{{resolve:ssm:/bpartners/${Env}/db/username}}'
      MasterUserPassword: !Sub '{{resolve:ssm:/bpartners/${Env}/db/password}}'
      DBSnapshotIdentifier: !Ref DBSnapshot
  DatabaseSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ['', [/bpartners/, !Ref Env, /db/url]]
      Type: String
      Value:
        Fn::Join:
          - ''
          - - jdbc:postgresql://
            - Fn::GetAtt:
                - Database
                - Endpoint.Address
            - ':'
            - Fn::GetAtt:
                - Database
                - Endpoint.Port
            - '/'
            - !Ref DBName

  Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  BucketSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ['', [/bpartners/, !Ref Env, /s3/bucket-name]]
      Type: String
      Value: !Ref Bucket

Outputs:
  DatabaseSSM:
    Value: !Ref DatabaseSSM
  BucketSSM:
    Value: !Ref BucketSSM
