INSERT INTO business_activity_template(name) VALUES ('Ardoisier');
INSERT INTO business_activity_template(name) VALUES ('Étancheur bitume');
INSERT INTO business_activity_template(name) VALUES ('Étancheur synthétique');
INSERT INTO business_activity_template(name) VALUES ('Bardeur-étancheur');
INSERT INTO business_activity_template(name) VALUES ('Architecte / maître d’œuvre');
INSERT INTO business_activity_template(name) VALUES ('Bureau d’études structures (bois/métal/béton)');
INSERT INTO business_activity_template(name) VALUES ('Bureau d’études enveloppe/thermique');
INSERT INTO business_activity_template(name) VALUES ('Diagnostiqueur amiante / plomb');
INSERT INTO business_activity_template(name) VALUES ('Thermographe / spécialiste humidité');
INSERT INTO business_activity_template(name) VALUES ('Géomètre / télépilote drone');
INSERT INTO business_activity_template(name) VALUES ('Charpentier bois');
INSERT INTO business_activity_template(name) VALUES ('Charpentier métallique / serrurier-métallier');
INSERT INTO business_activity_template(name) VALUES ('Maçon-couvreur');
INSERT INTO business_activity_template(name) VALUES ('Plombier-couvreur');
INSERT INTO business_activity_template(name) VALUES ('Applicateur résine / SEL');
INSERT INTO business_activity_template(name) VALUES ('Végétaliseur de toitures');
INSERT INTO business_activity_template(name) VALUES ('Poseur de fenêtres de toit / menuisier');
INSERT INTO business_activity_template(name) VALUES ('Façadier-bardeur');
INSERT INTO business_activity_template(name) VALUES ('Ferronnier / tôlier');
INSERT INTO business_activity_template(name) VALUES ('Intégrateur photovoltaïque (BIPV / surimposition)');
INSERT INTO business_activity_template(name) VALUES ('Installateur solaire thermique');
INSERT INTO business_activity_template(name) VALUES ('Climaticien / CVC toiture');
INSERT INTO business_activity_template(name) VALUES ('Échafaudeur');
INSERT INTO business_activity_template(name) VALUES ('Cordiste (travaux sur cordes)');
INSERT INTO business_activity_template(name) VALUES ('Poseur de systèmes antichute');
INSERT INTO business_activity_template(name) VALUES ('Ramoneur / fumiste');
INSERT INTO business_activity_template(name) VALUES ('Nettoyeur / démousseur');
INSERT INTO business_activity_template(name) VALUES ('Coupeur d’ardoises / tôlier-façonneur');
INSERT INTO business_activity_template(name) VALUES ('Entreprise de désamiantage (SS3/SS4)');

DELETE FROM business_activity_template WHERE name = 'Agenceur';
DELETE FROM business_activity_template WHERE name = 'Architecte';
DELETE FROM business_activity_template WHERE name = 'Architecte d''intérieur';
DELETE FROM business_activity_template WHERE name = 'Armurier';
DELETE FROM business_activity_template WHERE name = 'Artisan tout corps d''état';
DELETE FROM business_activity_template WHERE name = 'Barbier';
DELETE FROM business_activity_template WHERE name = 'Bottier';
DELETE FROM business_activity_template WHERE name = 'Boucher-charcutier';
DELETE FROM business_activity_template WHERE name = 'Boulanger';
DELETE FROM business_activity_template WHERE name = 'Brasseur';
DELETE FROM business_activity_template WHERE name = 'Carreleur';
DELETE FROM business_activity_template WHERE name = 'Céramiste';
DELETE FROM business_activity_template WHERE name = 'Chapiste';
DELETE FROM business_activity_template WHERE name = 'Charpentier';
DELETE FROM business_activity_template WHERE name = 'Chauffagiste';
DELETE FROM business_activity_template WHERE name = 'Chocolatier';
DELETE FROM business_activity_template WHERE name = 'Coiffeur/coiffeurse';
DELETE FROM business_activity_template WHERE name = 'Concepteur aménageur d''espaces intérieurs';
DELETE FROM business_activity_template WHERE name = 'Conducteur de travaux tout corps d''état';
DELETE FROM business_activity_template WHERE name = 'Confiseur';
DELETE FROM business_activity_template WHERE name = 'Constructeur Bois';
DELETE FROM business_activity_template WHERE name = 'Constructeur maison individuelle';
DELETE FROM business_activity_template WHERE name = 'Constructeur modulaire';
DELETE FROM business_activity_template WHERE name = 'Contractant travaux';
DELETE FROM business_activity_template WHERE name = 'Cordonnier';
DELETE FROM business_activity_template WHERE name = 'Coutelier';
DELETE FROM business_activity_template WHERE name = 'Cuisiniste';
DELETE FROM business_activity_template WHERE name = 'Décapeur';
DELETE FROM business_activity_template WHERE name = 'Décorateur';
DELETE FROM business_activity_template WHERE name = 'Décorateur ensemblier d''intérieur';
DELETE FROM business_activity_template WHERE name = 'Démolisseur';
DELETE FROM business_activity_template WHERE name = 'Dératiseur';
DELETE FROM business_activity_template WHERE name = 'Désamianteur';
DELETE FROM business_activity_template WHERE name = 'Designer d''intérieur';
DELETE FROM business_activity_template WHERE name = 'Designer textile';
DELETE FROM business_activity_template WHERE name = 'Dessinateur Projeteur';
DELETE FROM business_activity_template WHERE name = 'Diagnostiqueur humidité';
DELETE FROM business_activity_template WHERE name = 'Diagnostiqueur immobilier';
DELETE FROM business_activity_template WHERE name = 'Domotique';
DELETE FROM business_activity_template WHERE name = 'Ebeniste';
DELETE FROM business_activity_template WHERE name = 'Elagueur';
DELETE FROM business_activity_template WHERE name = 'Électricien';
DELETE FROM business_activity_template WHERE name = 'Electricien';
DELETE FROM business_activity_template WHERE name = 'Électronicien';
DELETE FROM business_activity_template WHERE name = 'Entreprise de rénovation et décoration';
DELETE FROM business_activity_template WHERE name = 'Entreprise générale du bâtiment';
DELETE FROM business_activity_template WHERE name = 'Etanchéiste';
DELETE FROM business_activity_template WHERE name = 'Etancheur';
DELETE FROM business_activity_template WHERE name = 'Façadier';
DELETE FROM business_activity_template WHERE name = 'Ferronnier';
DELETE FROM business_activity_template WHERE name = 'Fleuriste';
DELETE FROM business_activity_template WHERE name = 'Frigoriste';
DELETE FROM business_activity_template WHERE name = 'Fromager-Crémier';
DELETE FROM business_activity_template WHERE name = 'Gantier';
DELETE FROM business_activity_template WHERE name = 'Gemmogue';
DELETE FROM business_activity_template WHERE name = 'Génie civil';
DELETE FROM business_activity_template WHERE name = 'Géomètre';
DELETE FROM business_activity_template WHERE name = 'Glacier';
DELETE FROM business_activity_template WHERE name = 'Horloger';
DELETE FROM business_activity_template WHERE name = 'Installateur sanitaire';
DELETE FROM business_activity_template WHERE name = 'Jardinier';
DELETE FROM business_activity_template WHERE name = 'Jointeur';
DELETE FROM business_activity_template WHERE name = 'Luthier';
DELETE FROM business_activity_template WHERE name = 'Maçon';
DELETE FROM business_activity_template WHERE name = 'Maître d''œuvre';
DELETE FROM business_activity_template WHERE name = 'Marbrier';
DELETE FROM business_activity_template WHERE name = 'Maréchal Ferrant';
DELETE FROM business_activity_template WHERE name = 'Maroquinier';
DELETE FROM business_activity_template WHERE name = 'Menuisier';
DELETE FROM business_activity_template WHERE name = 'Métallier';
DELETE FROM business_activity_template WHERE name = 'Métallurgiste';
DELETE FROM business_activity_template WHERE name = 'Miroitier';
DELETE FROM business_activity_template WHERE name = 'Monteur d''échafaudages';
DELETE FROM business_activity_template WHERE name = 'Nettoyeur';
DELETE FROM business_activity_template WHERE name = 'Œnologue';
DELETE FROM business_activity_template WHERE name = 'Parfumeur';
DELETE FROM business_activity_template WHERE name = 'Parqueteur';
DELETE FROM business_activity_template WHERE name = 'Patissier';
DELETE FROM business_activity_template WHERE name = 'Paysagiste';
DELETE FROM business_activity_template WHERE name = 'Peintre';
DELETE FROM business_activity_template WHERE name = 'Peintre en bâtiment';
DELETE FROM business_activity_template WHERE name = 'Pisciniste';
DELETE FROM business_activity_template WHERE name = 'Plaquiste';
DELETE FROM business_activity_template WHERE name = 'Plasticien';
DELETE FROM business_activity_template WHERE name = 'Plâtrier';
DELETE FROM business_activity_template WHERE name = 'Plombier';
DELETE FROM business_activity_template WHERE name = 'Plombier-chauffagiste';
DELETE FROM business_activity_template WHERE name = 'Poissonnier';
DELETE FROM business_activity_template WHERE name = 'Ponceur';
DELETE FROM business_activity_template WHERE name = 'Ramoneur';
DELETE FROM business_activity_template WHERE name = 'Ravalement de façade';
DELETE FROM business_activity_template WHERE name = 'Rénovation d''intérieur';
DELETE FROM business_activity_template WHERE name = 'Restaurateur d''œuvres d''art';
DELETE FROM business_activity_template WHERE name = 'Revêtement de sol';
DELETE FROM business_activity_template WHERE name = 'Scieur-Carotteur de béton';
DELETE FROM business_activity_template WHERE name = 'Sellier';
DELETE FROM business_activity_template WHERE name = 'Sellier-harnacheur';
DELETE FROM business_activity_template WHERE name = 'Serrurier';
DELETE FROM business_activity_template WHERE name = 'Shaper';
DELETE FROM business_activity_template WHERE name = 'Staffeur';
DELETE FROM business_activity_template WHERE name = 'Staffeur - ornemaniste';
DELETE FROM business_activity_template WHERE name = 'Storiste';
DELETE FROM business_activity_template WHERE name = 'Tailleur de pierre';
DELETE FROM business_activity_template WHERE name = 'Tapissier';
DELETE FROM business_activity_template WHERE name = 'Taxidermiste';
DELETE FROM business_activity_template WHERE name = 'Technicien de curage';
DELETE FROM business_activity_template WHERE name = 'Technicien de sécurité';
DELETE FROM business_activity_template WHERE name = 'Technicien froid et climatisation';
DELETE FROM business_activity_template WHERE name = 'Technicien tout corps d''état';
DELETE FROM business_activity_template WHERE name = 'Terrassiers';
DELETE FROM business_activity_template WHERE name = 'Tonnelier';
DELETE FROM business_activity_template WHERE name = 'Tout corps d''état';
DELETE FROM business_activity_template WHERE name = 'Travaux d''aménagement urbain';
DELETE FROM business_activity_template WHERE name = 'Travaux d''isolation';
DELETE FROM business_activity_template WHERE name = 'Travaux publics';
DELETE FROM business_activity_template WHERE name = 'Vernisseur';
DELETE FROM business_activity_template WHERE name = 'Vitrailliste';
DELETE FROM business_activity_template WHERE name = 'Vitrier';

