name: CD compute

on:
  push:
    branches:
      - 'dev'
      - 'prod'
      - 'preprod'

  workflow_dispatch:
    inputs:
      run_tests:
        type: boolean
        required: false
        default: true

jobs:
  cd-compute:
    if: github.ref_name == 'dev' || github.ref_name == 'prod' || github.ref_name == 'preprod'

    runs-on: ubuntu-latest
    
    timeout-minutes: 45

    env:
      AWS_REGION: eu-west-3
      ECR_REPOSITORY: bpartners-api-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: From gradle.properties to version.yml
        run: |
          cp gradle.properties version.yml
          sed -i 's/=/: /g' version.yml

      - name: Read semantic version (needed by the docker image build)
        id: read-semver
        uses: CumulusDS/get-yaml-paths-action@v0.1.0
        with:
          file: version.yml
          version: version

      - name: Run tests
        run: |
          export DEV_USER_ACCESS_TOKEN=${{ secrets.DEV_USER_ACCESS_TOKEN }}
          export SWAN_CLIENT_ID=${{ secrets.SWAN_CLIENT_ID }}
          export SWAN_CLIENT_SECRET=${{ secrets.SWAN_CLIENT_SECRET }}
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ./gradlew test
        if: ${{ github.event.inputs.run_tests != 'false' }}

      - run: ./gradlew build -x test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up crendetials for private ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@aaf69d68aa3fb14c1d5a6be9ac61fe15b48453a2

      - name: Build, tag and push Docker image to AWS private ECR (continue-on-error)
        # Assume dev and prod point to the same commit.
        # Assume dev finished publishing the (immutable) image.
        # In such a case, prod publication will end in an error since image already exists:
        # Ignore the error and pursue to stack update.
        continue-on-error: true
        env:
          ECR_PRIVATE_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build --build-arg version=${{ steps.read-semver.outputs.version }} \
            -t $ECR_PRIVATE_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_PRIVATE_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Put branch_env into GITHUB_ENV
        run: echo "branch_env=${{ github.ref_name }}" >> $GITHUB_ENV


      - name: Get configurations from ecs-conf.yml
        id: get-configuration
        uses: CumulusDS/get-yaml-paths-action@v1.0.1
        with:
          file: ecs-conf.yml
          vCpu: envs.${{ env.branch_env }}.vCpu
          memory: envs.${{ env.branch_env }}.memory
          tasksDesiredCount: envs.${{ env.branch_env }}.tasksDesiredCount
          listenerRuleAvailablePriority: envs.${{ env.branch_env }}.listenerRuleAvailablePriority

      - name: Put outputs from get-configuration step into GITHUB_ENV
        run: |
          echo "vCpu=${{ steps.get-configuration.outputs.vCpu}}" >> $GITHUB_ENV
          echo "memory=${{ steps.get-configuration.outputs.memory}}" >> $GITHUB_ENV
          echo "tasksDesiredCount=${{ steps.get-configuration.outputs.tasksDesiredCount}}" >> $GITHUB_ENV
          echo "listenerRuleAvailablePriority=${{ steps.get-configuration.outputs.listenerRuleAvailablePriority}}" >> $GITHUB_ENV

      - name: Deploy compute stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.branch_env }}-compute-bpartners
          template: cf-stacks/compute-stack.yml
          tags: "[ { \"Key\": \"app\", \"Value\": \"bpartners\" }, { \"Key\": \"env\", \"Value\": \"${{ env.branch_env }}\" } ]"
          capabilities: CAPABILITY_NAMED_IAM
          no-fail-on-empty-changeset: "1"
          parameter-overrides:
            "Env=${{ env.branch_env }},
            ListenerRuleAvailablePriority=${{ env.listenerRuleAvailablePriority }},
            Image=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }},
            Cpu=${{ env.vCpu }}, Memory=${{ env.memory }}, TasksDesiredCount=${{ env.tasksDesiredCount }}"
