name: CD event 

on:
  push:
    branches: 
      - 'dev'
      - 'prod'
  
  workflow_dispatch:

jobs: 
  cd-event: 
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/prod'

    runs-on: ubuntu-latest

    timeout-minutes: 20

    env:
      AWS_REGION: eu-west-3
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Put branch_env into GITHUB_ENV
        run: |
          if ${{ github.ref == 'refs/heads/dev' }}; then
            echo "branch_env=dev" >> $GITHUB_ENV
          elif ${{ github.ref == 'refs/heads/prod' }}; then
            echo "branch_env=prod" >> $GITHUB_ENV
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Deploy event stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.branch_env }}-event-bpartners
          template: cf-stacks/event-stack.yml
          tags: "[ { \"Key\": \"app\", \"Value\": \"api\" }, { \"Key\": \"env\", \"Value\": \"${{ env.branch_env }}\" } ]"
          capabilities: CAPABILITY_NAMED_IAM
          no-fail-on-empty-changeset: "1"
          parameter-overrides:
            "Env=${{ env.branch_env }}" 