name: CD storage

on:
  push:
    branches:
      - 'prod'
      - 'preprod'

  workflow_dispatch:
    inputs:
      db_snapshot_identifier:
        type: string
        default: null
        required: false

jobs:
  cd-storage:
    if: github.ref_name == 'prod' || github.ref_name == 'preprod' || github.ref_name == 'preprod-private-url'

    runs-on: ubuntu-latest
    
    timeout-minutes: 20

    env:
      AWS_REGION: eu-west-3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Put branch_env into GITHUB_ENV
        run: |
            if ${{ github.ref_name == 'preprod' || github.ref_name == 'preprod-private-url' }}; then
              echo "branch_env=preprod" >> $GITHUB_ENV
            else
              echo "branch_env=${{ github.ref_name }}" >> $GITHUB_ENV
            fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy storage stack
        if: github.ref_name != 'preprod-private-url'
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.branch_env }}-storage-bpartners
          template: cf-stacks/storage-stack.yml
          tags: "[ { \"Key\": \"app\", \"Value\": \"bpartners\" }, { \"Key\": \"env\", \"Value\": \"${{ env.branch_env }}\" } ]"
          capabilities: CAPABILITY_NAMED_IAM
          no-fail-on-empty-changeset: "1"
          parameter-overrides:
            "Env=${{ env.branch_env }},
             DBSnapshot=${{ github.event.inputs.db_snapshot_identifier }}"

      - name: Deploy storage stack
        if: github.ref_name == 'preprod-private-url'
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: preprod-private-url-storage-bpartners
          template: cf-stacks/storage-stack.yml
          tags: "[ { \"Key\": \"app\", \"Value\": \"bpartners\" }, { \"Key\": \"env\", \"Value\": \"${{ env.branch_env }}\" } ]"
          capabilities: CAPABILITY_NAMED_IAM
          no-fail-on-empty-changeset: "1"
          parameter-overrides:
            "Env=${{ env.branch_env }},
             DBSnapshot=${{ github.event.inputs.db_snapshot_identifier }}"