name: CD storage

on:
  push:
    branches:
      - 'prod'
      - 'preprod'

  workflow_dispatch:
    inputs:
      db_snapshot_identifier:
        type: string
        default: null
        required: false

jobs:
  cd-storage:
    if: github.ref_name == 'prod' || github.ref_name == 'preprod'

    runs-on: ubuntu-latest

    timeout-minutes: 20

    env:
      AWS_REGION: eu-west-3

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Put branch_env into GITHUB_ENV
        run: |
          echo "branch_env=${{ github.ref_name }}" >> $GITHUB_ENV

      - uses: hei-school/aws-credentials-setter@v1.0.3
        with:
          secrets: ${{ toJSON(secrets) }}
          region: ${{ env.AWS_REGION }}

      - name: Deploy storage stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.branch_env }}-storage-bpartners
          template: cf-stacks/storage-database-stack.yml
          tags: "[ { \"Key\": \"app\", \"Value\": \"bpartners\" }, { \"Key\": \"env\", \"Value\": \"${{ env.branch_env }}\" } ]"
          capabilities: CAPABILITY_NAMED_IAM
          no-fail-on-empty-changeset: "1"
          parameter-overrides:
            "Env=${{ env.branch_env }},
             DBSnapshot=${{ github.event.inputs.db_snapshot_identifier }}"