name: Compute stack scheduler

on:
  schedule:
    - cron: '0 6 * * 1,2,3,4,5'
    - cron: '59 23 * * 1,2,3,4,5'

  workflow_dispatch:

jobs:
  delete_compute_stack:
    if: github.event.schedule == '59 23 * * 1,2,3,4,5'
    runs-on: ubuntu-latest
    steps:
      - name: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1.0.3
        with:
          version: 2
          verbose: false
          arch: amd64
          rootdir: ''
          workdir: ''

      - name: Connect to AWS
        run: sh ./.shell/initAWS.sh ${{ secrets.AWS_ACCESS_KEY_ID }} ${{ secrets.AWS_SECRET_ACCESS_KEY }} ${{ secrets.AWS_REGION }}

      - name: Put branch_env into GITHUB_ENV
        run: echo "branch_env=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: delete compute stack
        run: aws cloudformation delete-stack --stack-name ${{ env.branch_env }}-compute-bpartners

  deploy_compute_stack:
    if: github.event.schedule == '0 6 * * 1,2,3,4,5'
    uses: ./github/workflows/cd-compute.yml
    secrets: inherit