name: Sched Depl compute

on:
  schedule:
    - cron: '0 3 * * 1,2,3,4,5'

  workflow_dispatch:

jobs:
  deploy_compute_stack:
    if: github.ref_name == 'preprod'
    uses: ./.github/workflows/cd-compute.yml
    with:
      run_tests: false
    secrets: inherit